/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import DAO.*;
import Class.*;
import javax.swing.JOptionPane;
/**
 *
 * @author vuqua
 */
public class FormDangKy extends javax.swing.JFrame {

    /**
     * Creates new form FormDangKy
     */
    public FormDangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        txt_macongnhan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tencongnhan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_vitri = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_donvi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_mk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Đăng Ký Tài Khoản");

        a.setText("Mã User");

        jLabel3.setText("Tên User");

        jLabel4.setText("Vị Trí");

        cbx_vitri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worker", "Nhân viên" }));

        jLabel5.setText("Đơn vị");

        jButton1.setText("Đăng Ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2))
                    .addComponent(a))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_macongnhan)
                    .addComponent(txt_tencongnhan)
                    .addComponent(txt_donvi)
                    .addComponent(cbx_vitri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mk))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(txt_macongnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tencongnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbx_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_mk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      int role = cbx_vitri.getSelectedIndex();
        if (role == 0) {
            WorkerDAO workerDAO = new WorkerDAO();

            // Kiểm tra xem mã công nhân đã tồn tại hay chưa
            String maCongNhanToCheck = txt_macongnhan.getText();
            if (workerDAO.isMaCongNhanExists(maCongNhanToCheck)) {
                // Mã công nhân đã tồn tại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Mã công nhân đã tồn tại. Vui lòng chọn mã công nhân khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                // Mã công nhân chưa tồn tại, thực hiện đăng ký
                Worker newObj = new Worker();
                newObj.setMaCongNhan(txt_macongnhan.getText());
                newObj.setTenCongNhan(txt_tencongnhan.getText());
                newObj.setDonVi(txt_donvi.getText());
                newObj.setPassWord(txt_mk.getText());
                workerDAO.register(newObj);

                // Đóng form hiện tại
                this.dispose();

                // Mở form đăng nhập
                LoginWorker loginForm = new LoginWorker();
                loginForm.setVisible(true);
            }
        }
        if (role == 1) {
            LoginOfficer loginOfficer = new LoginOfficer();

            // Kiểm tra xem mã công nhân đã tồn tại hay chưa
            String maCongNhanToCheck = txt_macongnhan.getText();
            if (loginOfficer.isNhanVienExists(maCongNhanToCheck)) {
                // Mã công nhân đã tồn tại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Mã công nhân đã tồn tại. Vui lòng chọn mã công nhân khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                // Mã công nhân chưa tồn tại, thực hiện đăng ký
                Officer newObj = new Officer();
                newObj.setMaNhanVien(txt_macongnhan.getText());
                newObj.setTenNhanVien(txt_tencongnhan.getText());
                newObj.setDonVi(txt_donvi.getText());
                newObj.setPassWord(txt_mk.getText());
                loginOfficer.register(newObj);

                // Đóng form hiện tại
                this.dispose();

                // Mở form đăng nhập
                LoginNhanVien loginForm = new LoginNhanVien();
                loginForm.setVisible(true);
            }
        }

      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JComboBox<String> cbx_vitri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_donvi;
    private javax.swing.JTextField txt_macongnhan;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_tencongnhan;
    // End of variables declaration//GEN-END:variables
}
